spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/wxshop
    username: root
    password: 64793393
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath*:**/mappers/*.xml

wxshop:
  redis:
    host: 192.168.99.100:6379