server:
  port: 8081

spring:
  application:
    name: moudles-main
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/wxshop
    username: root
    password: 64793393
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:db/mybatis/mybatis-config.xml
  mapper-locations: classpath*:**/mappers/*.xml

wxshop:
  orderservice:
    version: 1.0.0
    url: ""
  redis:
    host: 192.168.99.100:6379

dubbo:
  registry:
    address: zookeeper://192.168.99.100:2181?timeout=1000000
